import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./Components/NavBar";
import { TanstackProvider } from "./providers/tanstackProvider";
import { TokenProvider } from "./contexts/TokenContext";
import AppListener from "./Components/AppListener";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
        suppressHydrationWarning={true}
      >
        <TokenProvider>
          <TanstackProvider>
            <AppListener />
            <NavBar />
            <main className="ml-40 bg-[#302e2b]">{children}</main>
          </TanstackProvider>
        </TokenProvider>
      </body>
    </html>
  );
}
