import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar, { NavBarMobile } from "./Components/NavBar";
import { TanstackProvider } from "./providers/tanstackProvider";
import AppListener from "./Components/AppListener";
import { NavigationEvents } from "./Components/NavigationEvents";
import { handleLeaveChallengePage } from "./challenge/[challengeId]/page";
import { ChallengeProvider } from "./contexts/ChallengeContext";
import ChallengeNotification from "./Components/ChallengeNotification";
import { NavbarProvider } from "./contexts/NavBarContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
        suppressHydrationWarning={true}
      >
        <ChallengeProvider>
          <NavbarProvider>
            <TanstackProvider>
              <NavigationEvents handleLeaveChallengePage={handleLeaveChallengePage} />
              <AppListener />
              <div className="sm:block hidden"><NavBar /></div>
              <div className="sm:hidden block"><NavBarMobile /></div>
              <ChallengeNotification />
              <main className="sm:ml-40 m-0 bg-[#302e2b] pt-10">{children}</main>
            </TanstackProvider>
          </NavbarProvider>
        </ChallengeProvider>
      </body>
    </html>
  );
}
